plugins:
  - jekyll-remote-theme
remote_theme: TaylanTatli/Moon
name: Fly, Crash, Throw Exception
description: Random stuff from Stefano Borini
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      category: "incomplete"
      comments: true
