title: Fly, Crash, Throw Exception
description: Random stuff from Stefano Borini
show_downloads: false
remote_theme: stefanoborini/cards

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      category: "incomplete"
      comments: true
